name: research
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python
  - python=3.12.1
  
  # Core Scientific Libraries
  - numpy=1.26.3
  - pandas=2.1.4
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.1
  
  # Machine Learning & Deep Learning
  - scikit-learn=1.3.2
  - xgboost=2.0.3
  - lightgbm=4.1.0
  - catboost=1.2.2
  - pytorch=2.1.2
  - torchvision=0.16.2
  - tensorflow=2.15.0
  - transformers=4.36.2  # Hugging Face Transformers
  
  # Statistical Testing & Analysis
  - statsmodels=0.14.1
  - pingouin=0.5.3  # advanced statistical tests
  - lifelines=0.27.8  # survival analysis
  
  # Optimization & Hyperparameter Tuning
  - optuna=3.4.0
  - hyperopt=0.2.7
  - bayesian-optimization=1.4.3
  - ray-tune=2.9.0  # distributed hyperparameter tuning
  
  # Acceleration & Performance
  - numba=0.58.1
  - dask=2023.12.1
  - vaex=4.17.0  # for handling large datasets
  - cython=3.0.7
  - cupy=13.0.0  # GPU acceleration
  
  # Reinforcement Learning
  - gym=0.26.2
  - stable-baselines3=2.2.1
  - tianshou=0.5.1  # modern RL framework
  
  # Visualization
  - plotly=5.18.0
  - bokeh=3.3.3
  - holoviews=1.18.1
  - panel=1.3.4  # interactive dashboards
  - altair=5.2.0  # declarative visualizations
  
  # Development Tools
  - black=23.12.1
  - ruff=0.1.9
  - pip=23.3.2
  - ipykernel=6.28.0
  
  # Additional Scientific Libraries
  - networkx=3.2.1  # graph operations
  - scikit-image=0.22.0  # image processing
  - umap-learn=0.5.5  # dimensionality reduction
  - hdbscan=0.8.33  # clustering
  
  # Experiment Tracking & MLOps
  - mlflow=2.9.2
  - wandb=0.16.1
  - dvc=3.38.1  # data version control
  
  # Utilities
  - tqdm=4.66.1
  - joblib=1.3.2
  - rich=13.7.0
  - typer=0.9.0
  - pydantic=2.5.3
  - loguru=0.7.2
  - pytest=7.4.4
  
  # Additional Dependencies
  - pip:
    - dynamicviz==1.0.0  # assuming version
    - optuna-dashboard==0.12.0
    - gradio==4.12.0  # UI for ML models
    - shap==0.44.0  # model interpretability
