name: y_241209
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12.2
  - anaconda
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - black
  - isort
  - flake8
  - pytest
  - pip
  - pip:
    - acres==0.1.0
    - bids-validator==1.14.7.post0
    - bidsschematools==0.11.3.post3
    - plotbin==3.1.7
    - puremagic==1.28
    - python-louvain==0.16
    - rdflib==6.3.2
    - simplejson==3.19.3
    - slir==0.5.1
    - teneto==0.5.3
    - universal-pathlib==0.2.5
