name: y_241209
channels:
  - defaults
dependencies:
  - python=3.12.2
  - pip
  - pip:
    # 基本的な科学計算パッケージ
    - numpy==1.26.4
    - pandas==2.2.3
    - scipy==1.13.1
    - matplotlib==3.9.2
    - seaborn==0.13.2
    # 神経科学関連パッケージ
    - nibabel==5.3.2
    - nipy==0.6.0
    - nilearn==0.10.4
    - nipype==1.9.1
    # 機械学習・最適化関連
    - scikit-learn==1.5.1
    - networkx==3.3.0
    - joblib==1.4.2
    - hdbscan==0.8.39
    - pacmap==0.7.6
    - optuna==4.1.0
    - hyperopt==0.2.7
    - bctpy==0.6.1
    # 統計解析
    - statannotations==0.7.1
    - pingouin==0.5.5
    # ユーティリティ
    - tqdm==4.67.1
    - jupyter==1.0.0
    - ipykernel==6.28.0