name: y_241209
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - optuna
  - black
  - ruff
  - pip
  - ipykernel
  - jupyter
  - tqdm
  - pytest
