name: base
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python
  - python=3.12.1
  
  # Core Scientific Libraries
  - numpy=1.26.3
  - pandas=2.1.4
  - matplotlib=3.8.2
  
  # Development Tools
  - black=23.12.1
  - ruff=0.1.9
  - pip=23.3.2
  - ipykernel=6.28.0
  - jupyter=1.0.0
  - pytest=7.4.4
  
  # Basic Utilities
  - tqdm=4.66.1
  - joblib=1.3.2
  
  # Additional Utilities
  - rich=13.7.0  # Better terminal output
  - typer=0.9.0  # CLI creation
  - pydantic=2.5.3  # Data validation
  - loguru=0.7.2  # Better logging
  
  # Version Control
  - pre-commit=3.6.0  # Git hooks management
