name: Build and Push Base Image

on:
  push:
    branches: [ main ]
    paths:
      - 'base/**'
      - '.github/workflows/docker-base.yml'
  workflow_dispatch:  # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate date-based version
        run: echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/research-env-base:latest
            ghcr.io/${{ github.repository_owner }}/research-env-base:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
